### ISSUE TITLE
Bump Mapping

### ISSUE THREAD

**Issue by harsssh** [harsssh/miniRT#18]
Height Mapのパスはパース済み. レイとの交点での法線 (`normal`) をいい感じに決めればできる?
https://github.com/harsssh/miniRT/blob/f4aa773e5b10465058a92fe2b3756a9fc3e2f59e/include/scene.h#L101-L110
https://github.com/harsssh/miniRT/blob/f4aa773e5b10465058a92fe2b3756a9fc3e2f59e/include/tracer.h#L24-L31

**Comment by smatsuodev** [comment]
@harsssh 
height mapってどんな感じの構造を想定してますか？このコードだと`.png`になってたので、もしかして画像として与える感じですか？
https://github.com/harsssh/miniRT/blob/944aeef14958d170a4a4a25be2c64c054a106034/src/scene/parse_line_object.c#L79

**Comment by harsssh** [comment]
> @harsssh 
> 
> height mapってどんな感じの構造を想定してますか？このコードだと`.png`になってたので、もしかして画像として与える感じですか？
> 
> https://github.com/harsssh/miniRT/blob/944aeef14958d170a4a4a25be2c64c054a106034/src/scene/parse_line_object.c#L79

画像を想定してます。mlxの機能で読み込めるはず。
https://harm-smits.github.io/42docs/libs/minilibx/images.html

**Comment by harsssh** [comment]
論文: https://dl.acm.org/doi/10.1145/965139.507101

**Comment by harsssh** [comment]
分かりやすい気がする: https://pbr-book.org/3ed-2018/Materials/Bump_Mapping
