### ISSUE TITLE
チェッカー柄

### ISSUE THREAD

**Issue by harsssh** [harsssh/miniRT#19]
オブジェクトに2つ目の色を指定して, チェッカー柄にできる.
https://github.com/harsssh/miniRT/blob/2e90178c68593ec8c01ba024150ef5bfe7bb2917/include/scene.h#L101-L110

**Comment by harsssh** [comment]
レイとの交点での物体の色 (`object_color`) をいい感じに決めればいい.
https://github.com/harsssh/miniRT/blob/f4aa773e5b10465058a92fe2b3756a9fc3e2f59e/include/tracer.h#L24-L31

**Comment by harsssh** [comment]
良さげ
https://zenn.dev/mebiusbox/books/8d9c42883df9f6/viewer/67a16c

**Comment by harsssh** [comment]
読んでないけど参考になりそう
http://raytracerchallenge.com/bonus/texture-mapping.html

**Comment by harsssh** [comment]
これも
https://inzkyk.xyz/ray_tracing_in_one_weekend/week_2/#%E6%9C%80%E5%88%9D%E3%81%AE%E3%83%86%E3%82%AF%E3%82%B9%E3%83%81%E3%83%A3%E3%82%AF%E3%83%A9%E3%82%B9-%E5%AE%9A%E6%95%B0%E3%83%86%E3%82%AF%E3%82%B9%E3%83%81%E3%83%A3

**Comment by smatsuodev** [comment]
planeのチェッカー柄、こいつを参考にしたんですが意味がわかりません。
https://gamedev.stackexchange.com/questions/172352/finding-texture-coordinates-for-plane

**Comment by harsssh** [comment]
> planeのチェッカー柄、こいつを参考にしたんですが意味がわかりません。
> 
> https://gamedev.stackexchange.com/questions/172352/finding-texture-coordinates-for-plane

法線ベクトルNと適当なベクトルとの外積を取ると、それは平面上のベクトルになります。これをe1とします。
さらに、Nとe1の外積をe2とすると、(e1, e2)は平面を張る、互いに直行するベクトルになります。
平面上のベクトルpとの内積、dot(e1, p)=|p|cosθ, dot(e2, p)=|p|cosφは(e1, e2)を軸とする"座標"になります。
(θはpとe1の間の角度、φはpとe2の間の角度。)

**Comment by smatsuodev** [comment]
なんとなく理解
ありがとうございます😊
